name: iOS-CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - qiita_reader_android/
      - qiita_reader_reactnative/
      - README.md
  pull_request:
    branches:
        - main
    paths-ignore:
      - qiita_reader_android/
      - qiita_reader_reactnative/
      - README.md
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app
  IOS_PROJECT_DIR: qiita_reader_ios

jobs:
  build:
    runs-on: macos-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v4

      # Xcodeバージョンの出力
      - name: Show Xcode version
        run: xcodebuild -version

      # ビルド
      - name: Xcode build
        working-directory: ${{ env.IOS_PROJECT_DIR }}
        run: |
          xcodebuild \
            -sdk iphonesimulator \
            -configuration Debug \
            -scheme QiitaReader \
            build
  unit_test:
    runs-on: macos-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v4

      # Xcodeバージョンの出力
      - name: Show Xcode version
        run: xcodebuild -version

      # テスト結果の解析ツールをインストール
      - name: Install tools (xcparse, xchtmlreport)
        run: |
          brew install chargepoint/xcparse/xcparse
          brew install xctesthtmlreport

      # テスト
      - name: Test
        working-directory: ${{ env.IOS_PROJECT_DIR }}
        run: |
          xcodebuild \
            -sdk iphonesimulator \
            -configuration Debug \
            -scheme QiitaReaderTests \
            -resultBundlePath UnitTestResults \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6' \
            test

      # テスト結果をHTMLとして生成
      - name: Generate HTML report from xcresult
        working-directory: ${{ env.IOS_PROJECT_DIR }}
        run: |
          mkdir -p TestReports
          xchtmlreport -r TestResults.xcresult -o TestReports

      # artifactとしてテスト結果をアップロード
      - name: Upload JSON result
        uses: actions/upload-artifact@v4
        with:
          name: UnitTestReports
          path: ${{ env.IOS_PROJECT_DIR }}/TestReports

      - name: Extract logs and screenshots using xcparse
        working-directory: ${{ env.IOS_PROJECT_DIR }}
        run: |
          mkdir -p TestArtifacts/Logs
          mkdir -p TestArtifacts/Screenshots
          xcparse logs TestResults.xcresult TestArtifacts/Logs
          xcparse screenshots TestResults.xcresult TestArtifacts/Screenshots

      - name: Upload raw test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RawTestArtifacts
          path: TestArtifacts
